# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

''' get dir names in current working path'''
# list to store folder names
list = []
root = r'C:\Users\DELL\Projects\EGSD Project Workspace'
for x in os.listdir(root):
    if os.path.isdir(os.path.join(root, x)):
        list.append(x)
        # print folder names
        print(x)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1200, 800)
        Form.setFixedSize(1200, 800)
        Form.setAutoFillBackground(False)

        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 1261, 861))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(225, 251, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 650, 511, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n""font: 20pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(870, 650, 241, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(225, 251, 255);\n""color: rgb(0, 0, 77);\n""border-radius:20;\n""border:2px solid black;\n""font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.run)
        self.pushButton.pressed.connect(self.clk)
        self.pushButton.released.connect(self.re)

        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(160, 460, 481, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n""border-radius:10;\n""border:2px solid black;\n""background-color: rgb(225, 251, 255);")
        self.comboBox.setObjectName("comboBox")

        #  add list items to combo box
        for i in range( len( list)):
            self.comboBox.addItem(list[i])
        #  function that call when select item in combo box
        self.comboBox.activated.connect(self.Pbutton)


        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(250, 40, 701, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Logo_of_MAS_Holdings.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Print Here"))
        self.pushButton.setText(_translate("Form", "RUN"))


    # --------------------------------------
    def Pbutton(self):
        # get the combo box selected item
        DirName = self.comboBox.currentText()
        # set text in the label
        self.label.setText(DirName)

    def clk(self):
        self.pushButton.setStyleSheet("background-color: rgb(225, 251, 255);\n""color: rgb(213, 213, 213);\n""border-radius:20;\n""border:2px solid black;\n""font: 20pt \"MS Shell Dlg 2\";")

        
    def re(self):
        self.pushButton.setStyleSheet("background-color: rgb(225, 251, 255);\n""color: rgb(0, 0, 77);\n""border-radius:20;\n""border:2px solid black;\n""font: 20pt \"MS Shell Dlg 2\";")
        
    # --------------------------------------------
    def run(self):
        self.label.setText("RUN button clicked")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
